--- #YAML:1.0
name:               Oktest
version:            0.0103
abstract:           a new-style testing library
author:
    - makoto kuwata <kwa@kuwata-lab.com>
license:            MIT-License
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Text::Diff:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
